---
## Author
author:
  name: Мазурский Александр Дмитриевич
  degrees: студент НКАбд-02-24
  email: 1132242468@pfur.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      postal-code: 117198
      city: Москва
      address: ул. Миклухо-Маклая, д. 6
## Title
title: Лабораторная работа №1
subtitle: Установка и конфигурация ОС на виртуальную машину
license: CC BY
date: 2025-03-06
date-format: "YYYY-MM-DD" # Example: 2025-09-06
---

# Информация

## Докладчик

:::::::::::::: {.columns align=center}
::: {.column width="70%"}

  * Мазурский Александр Дмитриевич
  * Студент НКАбд-02-24
  * Российский университет дружбы народов
  * [1132242468@pfur.ru](mailto:1132242468@pfur.ru)

:::
::: {.column width="30%"}

Место для изображения: фотография докладчика.

:::
::::::::::::::

# Цель работы

Целью данной работы является приобретение практических навыков установки операционной системы на виртуальную машину, настройки минимально необходимых для дальнейшей работы сервисов.

# Задание

- Установить Linux (Rocky) на виртуальную машину VirtualBox.
- Выполнить базовую конфигурацию системы и сетевых параметров.
- Подготовить систему для выполнения последующих лабораторных работ.

# Теоретическое введение

- Виртуализация позволяет запускать гостевые ОС в изолированной среде.
- VirtualBox поддерживает создание виртуальных дисков и подключение ISO-образов.
- После установки требуется базовая настройка пользователя, сети и имени хоста.

# Выполнение лабораторной работы

- Создал рабочий каталог в `/var/tmp` и указал его как папку ВМ в VirtualBox.

- Создал ВМ: Linux RedHat (64-bit), 2048 МБ RAM, VDI (динамический) 40 ГБ.


- Подключил ISO Rocky Linux, выбрал язык, окружение Server with GUI и Development Tools, отключил KDUMP.


- Задал имя узла `user.localdomain`, включил сеть, установил пароли root и администратора.


- Установил Guest Additions и проверил имя хоста через `hostnamectl`.



# Домашнее задание

- Проанализировал вывод `dmesg`, определил версию ядра, параметры CPU, объём памяти, тип гипервизора, тип ФС корня и порядок монтирования.
  Место для изображения: фрагменты вывода `dmesg`.

# Выводы

Установил Rocky Linux в VirtualBox, выполнил первичную конфигурацию системы и подтвердил корректные параметры загрузки.
